import necessary libraries

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pylab as plt
import seaborn as sns

Exploratory Data Analysis

In [2]:
df = pd.read_csv('../data/raw/SCFP2022.csv')
df.head()

,YY1,Y1,WGT,HHSEX,AGE,AGECL,EDUC,EDCL,MARRIED,KIDS,...,NWCAT,INCCAT,ASSETCAT,NINCCAT,NINC2CAT,NWPCTLECAT,INCPCTLECAT,NINCPCTLECAT,INCQRTCAT,NINCQRTCAT
0,1,11,3027.956120,2,70,5,9,3,2,2,...,4,2,4,2,1,8,3,3,2,1
1,1,12,3054.900065,2,70,5,9,3,2,2,...,4,2,5,2,1,8,3,3,2,1
2,1,13,3163.637766,2,70,5,9,3,2,2,...,4,2,4,2,1,8,3,3,1,1
3,1,14,3166.228463,2,70,5,9,3,2,2,...,3,2,4,1,1,6,3,2,1,1
4,1,15,3235.624715,2,70,5,9,3,2,2,...,3,2,4,2,1,8,3,3,1,1

In [3]:
df.shape

(22975, 357)

In [4]:
df.info

<bound method DataFrame.info of         YY1     Y1          WGT  HHSEX  AGE  AGECL  EDUC  EDCL  MARRIED  KIDS  \
0         1     11  3027.956120      2   70      5     9     3        2     2
1         1     12  3054.900065      2   70      5     9     3        2     2
2         1     13  3163.637766      2   70      5     9     3        2     2
3         1     14  3166.228463      2   70      5     9     3        2     2
4         1     15  3235.624715      2   70      5     9     3        2     2
...     ...    ...          ...    ...  ...    ...   ...   ...      ...   ...
22970  4603  46031  1705.225499      2   40      2     8     2        2     2
22971  4603  46032  1713.918975      2   40      2     8     2        2     2
22972  4603  46033  1689.140933      2   40      2     8     2        2     2
22973  4603  46034  1714.060239      2   40      2     8     2        2     2
22974  4603  46035  1692.039491      2   40      2     8     2        2     2

       ...  NWCAT  INCCAT  ASSETCAT  NINCCAT  NINC2CAT  NWPCTLECAT  \
0      ...      4       2         4        2         1           8
1      ...      4       2         5        2         1           8
2      ...      4       2         4        2         1           8
3      ...      3       2         4        1         1           6
4      ...      3       2         4        2         1           8
...    ...    ...     ...       ...      ...       ...         ...
22970  ...      1       2         1        2         1           1
22971  ...      1       2         1        1         1           1
22972  ...      1       2         1        2         1           1
22973  ...      1       2         1        2         1           1
22974  ...      1       2         1        2         1           1

       INCPCTLECAT  NINCPCTLECAT  INCQRTCAT  NINCQRTCAT
0                3             3          2           1
1                3             3          2           1
2                3             3          1           1
3                3             2          1           1
4                3             3          1           1
...            ...           ...        ...         ...
22970            3             3          2           1
22971            3             2          1           1
22972            3             3          2           1
22973            3             3          2           1
22974            3             3          1           1

[22975 rows x 357 columns]>

In [5]:
df.describe()

,YY1,Y1,WGT,HHSEX,AGE,AGECL,EDUC,EDCL,MARRIED,KIDS,...,NWCAT,INCCAT,ASSETCAT,NINCCAT,NINC2CAT,NWPCTLECAT,INCPCTLECAT,NINCPCTLECAT,INCQRTCAT,NINCQRTCAT
count,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,...,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000,22975.000000
mean,2302.597171,23028.971708,5715.185610,1.238955,54.468988,3.498368,10.328400,3.111164,1.367791,0.738629,...,3.055321,3.620022,3.647095,3.651273,1.859935,6.670729,6.603395,6.671425,2.771665,2.792644
std,1328.749586,13287.495936,4966.430219,0.426455,16.189081,1.556147,2.815743,1.026125,0.482215,1.108022,...,1.528703,1.829824,1.880664,1.822568,0.803743,3.669262,3.573612,3.560253,1.187083,1.180095
min,1.000000,11.000000,2.754882,1.000000,18.000000,1.000000,-1.000000,1.000000,1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1152.000000,11524.500000,1850.200822,1.000000,42.000000,2.000000,8.000000,2.000000,1.000000,0.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,3.000000,3.000000,4.000000,2.000000,2.000000
50%,2303.000000,23033.000000,4083.825044,1.000000,56.000000,4.000000,11.000000,3.000000,1.000000,0.000000,...,3.000000,4.000000,4.000000,4.000000,2.000000,7.000000,7.000000,7.000000,3.000000,3.000000
75%,3454.000000,34541.500000,8746.732248,1.000000,67.000000,5.000000,12.000000,4.000000,2.000000,1.000000,...,5.000000,6.000000,6.000000,6.000000,3.000000,10.000000,10.000000,10.000000,4.000000,4.000000
max,4603.000000,46035.000000,28265.283116,2.000000,95.000000,6.000000,14.000000,4.000000,2.000000,10.000000,...,5.000000,6.000000,6.000000,6.000000,3.000000,12.000000,12.000000,12.000000,4.000000,4.000000

In [6]:
df.isnull().sum().sum()

np.int64(0)

In [7]:
df['ASSET'].head()

0     957100.0
1    1067300.0
2     957200.0
3     828600.0
4     825600.0
Name: ASSET, dtype: float64

In [8]:
df['ASSET'].describe()

count    2.297500e+04
mean     2.031705e+07
std      1.109256e+08
min      0.000000e+00
25%      6.385000e+04
50%      5.398000e+05
75%      2.716900e+06
max      2.387781e+09
Name: ASSET, dtype: float64

In [9]:
df['DEBT'].describe()

count    2.297500e+04
mean     3.606429e+05
std      2.544356e+06
min      0.000000e+00
25%      0.000000e+00
50%      2.900000e+04
75%      2.170000e+05
max      1.319900e+08
Name: DEBT, dtype: float64

In [10]:
df['DEBT'].head()

0    195000
1    213000
2    279000
3    549000
4    223000
Name: DEBT, dtype: int64

In [11]:
df['WSAVED'].describe()

count    22975.000000
mean         2.460370
std          0.748047
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max          3.000000
Name: WSAVED, dtype: float64

In [12]:
df_si = df[df['Y1'].astype(str).str.endswith('1')].copy()
df_si.shape

(4595, 357)

In [13]:
list(df_si.columns)

['YY1',
 'Y1',
 'WGT',
 'HHSEX',
 'AGE',
 'AGECL',
 'EDUC',
 'EDCL',
 'MARRIED',
 'KIDS',
 'LF',
 'LIFECL',
 'FAMSTRUCT',
 'RACECL',
 'RACECL4',
 'RACECL5',
 'RACECL_EX',
 'RACE',
 'OCCAT1',
 'OCCAT2',
 'INDCAT',
 'FOODHOME',
 'FOODAWAY',
 'FOODDELV',
 'RENT',
 'INCOME',
 'WAGEINC',
 'BUSSEFARMINC',
 'INTDIVINC',
 'KGINC',
 'SSRETINC',
 'TRANSFOTHINC',
 'PENACCTWD',
 'NORMINC',
 'WSAVED',
 'SAVED',
 'SAVRES1',
 'SAVRES2',
 'SAVRES3',
 'SAVRES4',
 'SAVRES5',
 'SAVRES6',
 'SAVRES7',
 'SAVRES8',
 'SAVRES9',
 'SPENDMOR',
 'SPENDLESS',
 'EXPENSHILO',
 'LATE',
 'LATE60',
 'HPAYDAY',
 'BNKRUPLAST5',
 'KNOWL',
 'YESFINRISK',
 'NOFINRISK',
 'CRDAPP',
 'TURNDOWN',
 'FEARDENIAL',
 'TURNFEAR',
 'FORECLLAST5',
 'EMERGBORR',
 'EMERGSAV',
 'EMERGPSTP',
 'EMERGCUT',
 'EMERGWORK',
 'HBORRFF',
 'HBORRCC',
 'HBORRALT',
 'HBORRFIN',
 'HSAVFIN',
 'HSAVNFIN',
 'HPSTPPAY',
 'HPSTPLN',
 'HPSTPOTH',
 'HCUTFOOD',
 'HCUTENT',
 'HCUTOTH',
 'FINLIT',
 'BSHOPNONE',
 'BSHOPGRDL',
 'BSHOPMODR',
 'ISHOPNONE',
 'ISHOPGRDL',
 'ISHOPMODR',
 'BCALL',
 'BMAGZNEWS',
 'BMAILADTV',
 'BINTERNET',
 'BFRIENDWORK',
 'BFINPRO',
 'BSELF',
 'BDONT',
 'BOTHER',
 'ICALL',
 'IMAGZNEWS',
 'IMAILADTV',
 'IINTERNET',
 'IFRIENDWORK',
 'IFINPRO',
 'ISELF',
 'IDONT',
 'IOTHER',
 'BFINPLAN',
 'IFINPLAN',
 'INTERNET',
 'CHECKING',
 'HCHECK',
 'NOCHK',
 'EHCHKG',
 'WHYNOCKG',
 'DONTWRIT',
 'MINBAL',
 'DONTLIKE',
 'SVCCHG',
 'CANTMANG',
 'NOMONEY',
 'CREDIT',
 'DONTWANT',
 'OTHER',
 'CKLOCATION',
 'CKLOWFEEBAL',
 'CKMANYSVCS',
 'CKRECOMFRND',
 'CKPERSONAL',
 'CKCONNECTN',
 'CKLONGTIME',
 'CKSAFETY',
 'CKCONVPAYRL',
 'CKOTHCHOOSE',
 'PREPAID',
 'SAVING',
 'HSAVING',
 'MMDA',
 'MMMF',
 'MMA',
 'HMMA',
 'CALL',
 'HCALL',
 'LIQ',
 'HLIQ',
 'CDS',
 'HCDS',
 'STMUTF',
 'TFBMUTF',
 'GBMUTF',
 'OBMUTF',
 'COMUTF',
 'OMUTF',
 'NMMF',
 'HNMMF',
 'STOCKS',
 'HSTOCKS',
 'NSTOCKS',
 'WILSH',
 'NOTXBND',
 'MORTBND',
 'GOVTBND',
 'OBND',
 'BOND',
 'HBOND',
 'IRAKH',
 'THRIFT',
 'FUTPEN',
 'CURRPEN',
 'RETQLIQ',
 'HRETQLIQ',
 'ANYPEN',
 'DBPLANCJ',
 'DCPLANCJ',
 'DBPLANT',
 'BPLANCJ',
 'SAVBND',
 'HSAVBND',
 'CASHLI',
 'HCASHLI',
 'ANNUIT',
 'TRUSTS',
 'OTHMA',
 'HOTHMA',
 'OTHFIN',
 'HOTHFIN',
 'EQUITY',
 'HEQUITY',
 'DEQ',
 'RETEQ',
 'EQUITINC',
 'HBROK',
 'HTRAD',
 'NTRAD',
 'FIN',
 'HFIN',
 'VEHIC',
 'HVEHIC',
 'BUSVEH',
 'NBUSVEH',
 'OWN',
 'NOWN',
 'LEASE',
 'NLEASE',
 'VLEASE',
 'NVEHIC',
 'NEWCAR1',
 'NEWCAR2',
 'FARMBUS',
 'HOUSES',
 'HHOUSES',
 'HOUSECL',
 'ORESRE',
 'HORESRE',
 'NNRESRE',
 'HNNRESRE',
 'BUS',
 'ACTBUS',
 'NONACTBUS',
 'HBUS',
 'OTHNFIN',
 'HOTHNFIN',
 'NFIN',
 'HNFIN',
 'NHNFIN',
 'ASSET',
 'HASSET',
 'HELOC',
 'MRTHEL',
 'NH_MORT',
 'HOMEEQ',
 'HMRTHEL',
 'HHELOC',
 'HNH_MORT',
 'HPRIM_MORT',
 'PURCH1',
 'REFIN_EVER',
 'HEXTRACT_EVER',
 'HSEC_MORT',
 'PURCH2',
 'HMORT2',
 'HELOC_YN',
 'OTHLOC',
 'HOTHLOC',
 'MORT1',
 'MORT2',
 'MORT3',
 'RESDBT',
 'HRESDBT',
 'CCBAL',
 'NOCCBAL',
 'HCCBAL',
 'BNPL',
 'NOBNPL',
 'HBNPL',
 'VEH_INST',
 'EDN_INST',
 'INSTALL',
 'OTH_INST',
 'HVEH_INST',
 'HEDN_INST',
 'HOTH_INST',
 'HINSTALL',
 'ODEBT',
 'HODEBT',
 'DEBT',
 'HDEBT',
 'NETWORTH',
 'LEVRATIO',
 'DEBT2INC',
 'KGHOUSE',
 'KGORE',
 'KGBUS',
 'FARMBUS_KG',
 'KGSTMF',
 'KGTOTAL',
 'PAYMORT1',
 'PAYMORT2',
 'PAYMORT3',
 'PAYMORTO',
 'PAYLOC1',
 'PAYLOC2',
 'PAYLOC3',
 'PAYLOCO',
 'PAYHI1',
 'PAYHI2',
 'PAYLC1',
 'PAYLC2',
 'PAYLCO',
 'PAYORE1',
 'PAYORE2',
 'PAYOREV',
 'PAYORE3',
 'PAYVEH1',
 'PAYVEH2',
 'PAYVEH3',
 'PAYVEH4',
 'PAYVEHM',
 'PAYVEO1',
 'PAYVEO2',
 'PAYVEOM',
 'PAYEDU1',
 'PAYEDU2',
 'PAYEDU3',
 'PAYEDU4',
 'PAYEDU5',
 'PAYEDU6',
 'PAYEDU7',
 'PAYILN1',
 'PAYILN2',
 'PAYILN3',
 'PAYILN4',
 'PAYILN5',
 'PAYILN6',
 'PAYILN7',
 'PAYMARG',
 'PAYINS',
 'PAYPEN1',
 'PAYPEN2',
 'PAYPEN3',
 'PAYPEN4',
 'PAYPEN5',
 'PAYPEN6',
 'TPAY',
 'MORTPAY',
 'CONSPAY',
 'REVPAY',
 'PIRTOTAL',
 'PIRMORT',
 'PIRCONS',
 'PIRREV',
 'PIR40',
 'PLOAN1',
 'PLOAN2',
 'PLOAN3',
 'PLOAN4',
 'PLOAN5',
 'PLOAN6',
 'PLOAN7',
 'PLOAN8',
 'LLOAN1',
 'LLOAN2',
 'LLOAN3',
 'LLOAN4',
 'LLOAN5',
 'LLOAN6',
 'LLOAN7',
 'LLOAN8',
 'LLOAN9',
 'LLOAN10',
 'LLOAN11',
 'LLOAN12',
 'NWCAT',
 'INCCAT',
 'ASSETCAT',
 'NINCCAT',
 'NINC2CAT',
 'NWPCTLECAT',
 'INCPCTLECAT',
 'NINCPCTLECAT',
 'INCQRTCAT',
 'NINCQRTCAT']

First iteration of selected features to keep

In [14]:
columns = [
    # financial indicators 
    "NETWORTH",      
    "INCOME",
    "FIN",
    "NFIN",
    "DEBT",

    # investments / assets
    "EQUITY",
    "STOCKS",
    "HHOUSES",
    "BUS",

    # retirement-specific
    "RETQLIQ",

    # behavior / risk
    "YESFINRISK",
    "SPENDMOR",
    "LATE",
    "EMERGSAV",

    # liquidity
    "LIQ",

    # financial capability
    "FINLIT",

    # demographics
    "AGE",
    "EDUC",
    "MARRIED",
    "KIDS",

    # employment proxy
    "OCCAT1",
]

In [15]:
df_si[columns].head()

,NETWORTH,INCOME,FIN,NFIN,DEBT,EQUITY,STOCKS,HHOUSES,BUS,RETQLIQ,...,SPENDMOR,LATE,EMERGSAV,LIQ,FINLIT,AGE,EDUC,MARRIED,KIDS,OCCAT1
0,762100.0,38804.734469,258100,699000.0,195000,49000.0,0,1,0,245000,...,5,0,1,13100,1,70,9,2,2,3
5,721800.0,224829.659320,140500,1100000.0,518700,30000.0,0,1,460000,100000,...,3,0,1,40500,3,46,12,2,0,2
10,43597590.0,445335.671340,60492890,684700.0,17580000,60482000.0,59680000,1,0,459000,...,3,1,1,10890,3,68,14,1,0,3
15,2203000.0,152408.567130,2163000,40000.0,0,1724000.0,0,0,0,1499000,...,3,0,1,164000,3,74,12,2,0,3
20,4100.0,56207.414830,1100,14000.0,11000,0.0,0,0,0,0,...,2,0,0,1100,0,19,8,1,0,1

In [16]:
df_si[columns].describe()

,NETWORTH,INCOME,FIN,NFIN,DEBT,EQUITY,STOCKS,HHOUSES,BUS,RETQLIQ,...,SPENDMOR,LATE,EMERGSAV,LIQ,FINLIT,AGE,EDUC,MARRIED,KIDS,OCCAT1
count,4.595000e+03,4.595000e+03,4.595000e+03,4.595000e+03,4.595000e+03,4.595000e+03,4.595000e+03,4595.000000,4.595000e+03,4.595000e+03,...,4595.000000,4595.000000,4595.000000,4.595000e+03,4595.000000,4595.000000,4595.000000,4595.000000,4595.000000,4595.000000
mean,1.976343e+07,1.593197e+06,8.323474e+06,1.180529e+07,3.653292e+05,5.755701e+06,3.274774e+06,0.677040,9.059568e+06,5.972037e+05,...,3.506638,0.113384,0.492274,7.702663e+05,2.303591,54.468988,10.327965,1.367791,0.738629,1.830686
std,1.090717e+08,1.233521e+07,6.379025e+07,6.990782e+07,2.630899e+06,5.471745e+07,4.898205e+07,0.467658,6.108943e+07,3.177822e+06,...,1.359158,0.317096,0.499995,8.239290e+06,0.829303,16.190491,2.816657,0.482257,1.108118,0.933612
min,-5.555000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,...,1.000000,0.000000,0.000000,0.000000e+00,0.000000,18.000000,-1.000000,1.000000,0.000000,1.000000
25%,3.590500e+04,4.215556e+04,5.290000e+03,3.195000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,...,2.000000,0.000000,0.000000,1.935000e+03,2.000000,42.000000,8.000000,1.000000,0.000000,1.000000
50%,3.871000e+05,9.403933e+04,9.640000e+04,3.720000e+05,2.900000e+04,1.690000e+04,0.000000e+00,1.000000,0.000000e+00,1.800000e+04,...,4.000000,0.000000,0.000000,1.460000e+04,3.000000,56.000000,11.000000,1.000000,0.000000,2.000000
75%,2.479450e+06,2.648234e+05,1.006315e+06,1.305500e+06,2.162750e+05,4.750000e+05,3.900000e+03,1.000000,3.000000e+03,3.500000e+05,...,5.000000,0.000000,1.000000,9.960000e+04,3.000000,67.000000,12.000000,2.000000,1.000000,3.000000
max,2.178242e+09,4.532588e+08,1.924763e+09,1.341870e+09,1.238900e+08,1.788484e+09,1.786080e+09,1.000000,1.293850e+09,1.492700e+08,...,5.000000,1.000000,1.000000,2.676600e+08,3.000000,95.000000,14.000000,2.000000,10.000000,4.000000

In [17]:
filtered_df = df_si[columns]
filtered_df.shape

(4595, 21)

In [18]:
df.shape

(22975, 357)

In [19]:
filtered_df['RETQLIQ']

0         245000
5         100000
10        459000
15       1499000
20             0
          ...
22950    1944000
22955     450000
22960       3300
22965      54000
22970          0
Name: RETQLIQ, Length: 4595, dtype: int64

Derived RET_ASSETS combines broader financial assets and retirement liquid assets to better capture households with substantial non-retirement financial resources.

In [20]:
# create improved retirement asset target variable
filtered_df["RET_ASSETS"] = filtered_df["FIN"] + filtered_df["RETQLIQ"]

filtered_df[["FIN", "RETQLIQ", "RET_ASSETS"]].head(20)

         FIN  RETQLIQ  RET_ASSETS
0     258100   245000      503100
5     140500   100000      240500
10  60492890   459000    60951890
15   2163000  1499000     3662000
20      1100        0        1100
25   5728000   795000     6523000
30  13436800  1729500    15166300
35      1500        0        1500
40    295000        0      295000
45     27950        0       27950
50     20500        0       20500
55      1950        0        1950
60    204000    41000      245000
65       510        0         510
70     43620     7350       50970
75      3290        0        3290
80      2650        0        2650
85    428100   320000      748100
90     13000        0       13000
95      2500        0        2500

In [21]:
percent_fin_greater = (filtered_df["FIN"] > filtered_df["RETQLIQ"]).mean() * 100

print(f"{percent_fin_greater:.2f}% of rows have FIN greater than RETQLIQ")

98.80% of rows have FIN greater than RETQLIQ

In [22]:
filtered_df.to_csv('../data/filtered/Fil_SCF_20022.csv')